---
name: Lint and Test
on:
  - push
  - pull_request

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v4

      - name: Pre Commit Checks
        uses: pre-commit/action@v3.0.0

  unit-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: cargo test --verbose
